apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: metaname
  description: Replace me with a real description.
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: my-team